services:
  stellar-rpc-node-instance-pubnet1:
    ports:
      - "8003:8000"
    image: stellar-rpc-node-instance-pubnet
    restart: always

  stellar-rpc-node-instance-pubnet2:
    ports:
      - "8004:8000"
    image: stellar-rpc-node-instance-pubnet
    restart: always

  stellar-rpc-node-instance-pubnet3:
    ports:
      - "8005:8000"
    image: stellar-rpc-node-instance-pubnet
    restart: always
