services:
  rpc1:
    build: .
    platform: linux/amd64
    ports:
      - "8003:8000"
    volumes:
      - ./config:/opt/stellar
      - ./data:/opt/stellar/data
    restart: always

  rpc2:
    build: .
    platform: linux/amd64
    ports:
      - "8004:8000"
    volumes:
      - ./config:/opt/stellar
      - ./data:/opt/stellar/data
    restart: always

  rpc3:
    build: .
    platform: linux/amd64
    ports:
      - "8005:8000"
    volumes:
      - ./config:/opt/stellar
      - ./data:/opt/stellar/data
    restart: always
